import {useRouter} from 'next/router'
import Head from 'next/head';
import Navbar from '../../Components/Navbar/Navbar';
import styles from '../../styles/Watch.module.css';
import SidebarVideoCard from '../../Components/Cards/SidebarVideoCards';

const Watch = () => {

    const router = useRouter();
    const {v_id} = router.query;

   let demoData = {thumbnail:"/Assets/Img/youtube-logo.png",profilePic:"/Assets/Img/YouTube-Logo.png" ,title:"How To create and upload a video on youtube",channelName:"youtuberChannel",totalViews:132,uploadedTime:"1 day ago"}

    return(
        <div>
            <Head>
                <title>YouTube Clone</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="https://www.youtube.com/s/desktop/01530da7/img/favicon.ico" />
                <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet" />
            </Head>

            <Navbar/>

            <main className={styles.mainContainer}> 

               <div className={styles.leftColumn}>
                <div className={styles.videoContainer}>
                    <video width="320" height="240" controls className={styles.video}>  
                            <source src="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ElephantsDream.mp4" />
                    </video>
                </div>
                <div className={styles.videoInfo}>
                    <div className={styles.tags}>
                        <p> #TagCertified </p>
                        <p> #Tag2 </p>
                        <p> #TagOnTheFloor</p>
                    </div>
                    
                    <p className={styles.videoTitle}>Title of video - Tag On The Floor </p>

                    <div className={styles.videoOptions}>
                        <p className={styles.viewsAndDate}> 265,882,504 views . 16 Oct 2020 </p>
                        <div className={styles.option}>

                        </div>
                    </div>

                    <hr></hr>
                </div>
                  
               </div>

               <div className={styles.sidebar}> 
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
                  <SidebarVideoCard {...demoData }/>
               </div>

            </main>

        </div>
    )
}

export default Watch;